### ISSUE TITLE
Configuration requirements for Stable Diffusion fine-tuning

### ISSUE THREAD

**Issue by potentialming** [bbaaii/DreamDiffusion#21]
What a great job. I would like to ask about the configuration requirements required for fine-tuning this stable Diffusion. When I tried fine-tuning, I found that there were too many open files. Even though I adjusted the upper limit, it was still not enough. Very much looking forward to getting your answer.

**Comment by mahui-HUE** [comment]
您是怎么解决的，另外，显卡内存是否溢出了？

**Comment by potentialming** [comment]
> 您是怎么解决的，另外，显卡内存是否溢出了？

忘了怎么解决的了，我记得好像还是因为环境配置问题，我记得显卡内存在24G 3090上完全没有问题。
